### ISSUE TITLE
remove `rm`

### ISSUE THREAD

**Issue by ddsharpe** [sunnyvale-it/oracle-weblogic-apple-arm64-docker-image#1]
https://github.com/sunnyvale-it/oracle-weblogic-apple-arm64-docker-image/blob/b6549ec41f1d5e6b0aa59fe85d12cba6dc80d124/12.2.1.4/Dockerfile#L36

Assuming these Dockerfiles are for troubleshooting, and not production images, the `rm` commands should be removed from the install step.  We want to keep everything.

If its the installer itself that is failing, the installer log is deleted by the build tool (Docker, Podman, ...).  To make that file visible, you need to dump it to standard out or error.  Something like
```shell
&& test $? -eq 0 && chmod -R g+r /u01/oracle || (cat /tmp/OraInstall*/install*.log && exit 1)
```
If the exit code of the install is non-zero, cat the installer log

**Comment by denismaggior8** [comment]
Thanks @ddsharpe, here's the output.

I have modified the 12.2.1.4/Dockerfile as you suggested (also pushed here for your review)
Then executed the commands:

```console
$ cd 12.2.1.4/
$ docker build -t sunnyvaleit/oracle-weblogic:12.2.1.4-java8 .
```

[output.log](https://github.com/sunnyvale-it/oracle-weblogic-apple-arm64-docker-image/files/8790661/output.log)

Please advise.
Denis

**Comment by ddsharpe** [comment]
The code that is failing is in the Oracle installer.  That code fails when "exists" or "getParent" methods fail on oracle.installer.startup_location.  From line 115, I wonder if the new Mac ARM OS is giving Java trouble when creating the temporary directory where the installer is extracting its files.  This looks suspicious:
oracle.installer.startup_location=/tmp/orcl6802335180405305924.tmp/Disk1/install/unknown.  There shouldn't be an "unknown" folder there.  
As far as I know, the Oracle Java team only implemented MacOS ARM support for Java 17 (which WLS 12.2.1.4 does not support).  Its not clear that this is the problem, but it wouldn't be too hard to test.

**Comment by ddsharpe** [comment]
Can you try running the same job with JDK 17?  I don't care if WLS works at this point, only if the installer and the JDK do the right thing.

**Comment by denismaggior8** [comment]
Hi @ddsharpe, I've tested the installer using jdk-17.0.3.1_linux-aarch64_bin.tar.gz (Dockerfile in 12.2.1.4 folder updated and pushed for your review), the error changed to the one here reported:

```
Step 10/10 : RUN ${JAVA_HOME}/bin/java -jar /u01/$FMW_JAR -silent -responseFile /u01/install.file -invPtrLoc /u01/oraInst.loc -jreLoc ${JAVA_HOME} -ignoreSysPrereqs -force -novalidation ORACLE_HOME=$ORACLE_HOME INSTALL_TYPE="WebLogic Server" &&     test $? -eq 0 && chmod -R g+r /u01/oracle || (cat /tmp/OraInstall*/install*.log && exit 1)
 ---> Running in 6ae9da11dcda
Launcher log file is /tmp/OraInstall2022-06-01_05-37-21PM/launcher2022-06-01_05-37-21PM.log.
Extracting the installer . . . . Done
Checking if CPU speed is above 300 MHz.  Actual unknown.   Failed <<<<
Checking swap space: must be greater than 512 MBChecking if this platform requires a 64-bit JVM.   Actual 64    Passed (64-bit not required)
Checking temp space: must be greater than 300 MB.   Actual 204727 MB    Passed

>>> Ignoring failure(s) of required prerequisite checks and continuing.
Preparing to launch the Oracle Universal Installer from /tmp/OraInstall2022-06-01_05-37-21PM
Log: /tmp/OraInstall2022-06-01_05-37-21PM/install2022-06-01_05-37-21PM.log
Jun 01, 2022 5:37:23 PM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:94)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:331)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:289)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:212)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:174)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:345)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:482)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:445)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:356)
        at oracle.as.install.engine.config.xml.EngineConfigParser.getEngineConfig(EngineConfigParser.java:65)
        at oracle.as.install.engine.InstallEngine.startOperation(InstallEngine.java:442)
        at oracle.sysman.oio.oioc.OiocOneClickInstaller.main(OiocOneClickInstaller.java:717)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.lang.Class.getMethod(Class.java:2227)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:201)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        ... 31 more

java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:311)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:97)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:87)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:285)
        at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:94)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:128)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:331)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:289)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:212)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:174)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:345)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:482)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:445)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:356)
        at oracle.as.install.engine.config.xml.EngineConfigParser.getEngineConfig(EngineConfigParser.java:65)
        at oracle.as.install.engine.InstallEngine.startOperation(InstallEngine.java:442)
        at oracle.sysman.oio.oioc.OiocOneClickInstaller.main(OiocOneClickInstaller.java:717)
java.lang.NullPointerException: Cannot invoke "oracle.as.install.engine.modules.silent.log.SilentInstallTextLogger.printError(String)" because "this.m_consoleHandler" is null
        at oracle.as.install.engine.InstallEngine.startOperation(InstallEngine.java:492)
        at oracle.sysman.oio.oioc.OiocOneClickInstaller.main(OiocOneClickInstaller.java:717)
Unable to copy the logs to the permanent location: The permanent log directory is unknown (null)..

The log(s) can be found here: /tmp/OraInstall2022-06-01_05-37-21PM.
```  

Root cause seems to be

```
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
```

A question: does Weblogic 14 support JDK 17? As an alternative to the installer, is there any other mean to get Weblogic installed? (for example zip distributions)

**Comment by ddsharpe** [comment]
Supported, I didn't look.  But the install should work.  I just ran it on my Mac (Intel).
```console
[laptop]:bin $ imagetool create --tag w:1 --version 14.1.1.0.0 --jdkVersion 17u1^C
[laptop]:bin $ imagetool inspect -i w:1
[INFO   ] Inspecting w:1, this may take a few minutes if the image is not available locally.
{
  "os" : {
    "id" : "ol",
    "name" : "Oracle Linux Server",
    "version" : "8.6"
  },
  "javaHome" : "/u01/jdk",
  "javaVersion" : "17.0.3.1",
  "oracleHome" : "/u01/oracle",
  "oracleHomeGroup" : "oracle",
  "oracleHomeUser" : "oracle",
  "oracleInstalledProducts" : "WLS,COH,TOPLINK",
  "packageManager" : "MICRODNF",
  "wlsVersion" : "14.1.1.0.0"
}
```

**Comment by denismaggior8** [comment]
I've just tried to build an image with Oracle Linux 8, JDK 17 for ARM64 and WLS 14 (please refer to [this](https://raw.githubusercontent.com/sunnyvale-it/oracle-weblogic-apple-arm64-docker-image/master/14.1.1.0/Dockerfile) Dockerfile), the error is still "Unable to locate the startup/shiphome directory"

[wls14_jdk_17_output.log](https://github.com/sunnyvale-it/oracle-weblogic-apple-arm64-docker-image/files/8821683/wls14_jdk_17_output.log)

**Comment by ddsharpe** [comment]
I am getting a 404 trying to get to that Dockerfile.

**Comment by denismaggior8** [comment]
Sorry, please refer to: https://raw.githubusercontent.com/sunnyvale-it/oracle-weblogic-apple-arm64-docker-image/master/14.1.1.0/Dockerfile

**Comment by denismaggior8** [comment]
A small update: I started a WebLogic 12.2.1.4 container from the x86 Oracle's official image (using QEMU to emulate the x86 architecture), then I copied the /opt/oracle folder on my host machine in order to obtain an "zip distribution" of WebLogic. 

With another Dockerfile, made to build an ARM-native image, I just copied the "oracle" folder and built the image, this provided me the correspondent oracle/weblogic:12.2.1.4 image, but this time made for aarch64 architecture.

Then, following the example at https://github.com/oracle/docker-images/tree/main/OracleWebLogic/samples/12213-domain-home-in-image, I used my ARM-native Weblogic base image to create a WebLogic domain and it worked, thus WebLogic (installer a part) DOES work on ARM architecture ;-)

**Comment by ddsharpe** [comment]
Thank you for the update.  I acquired access to an M1 Mac yesterday and ran some tests without Docker.  The Oracle installer fails in the same way on the local host with the ARM JDKs.  In emulated mode, JDK8 for Intel with the same 12.2.1.4 installer works fine.  I filed a bug for the installer team.

**Comment by denismaggior8** [comment]
Thank you! I really think the M1 processor family must be supported in some way. In the meantime I would use WebLogic on ARM following the procedure I described here before.

Please keep me posted!
